
#define CORE_DEBUG_LEVEL 3 // 0..5
//#define IOTWEBCONF_DEBUG_PWD_TO_SERIAL
#define CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
#define CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED
#define NO_GLOBAL_ARDUINOOTA
